language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - TYPE=UNIT_TEST
  - TYPE=VALIDATION
  - TYPE=STATIC_ANALYSIS

os:
  - linux

matrix:
  include:
    - php: 7.2
      env: STATIC_ANALYSIS=true
  fast_finish: true
  allow_failures:
    - env: TYPE=VALIDATION
    - env: TYPE=STATIC_ANALYSIS

cache:
  directories:
    - validation/frameworks

before_script:
  - if [[ $STATIC_ANALYSIS = true ]]; then composer require phpstan/phpstan --no-update; fi
  - composer install
  - set -e # Stop on first error.
  - phpenv config-rm xdebug.ini
  - if find . -name "*.php" -path "./src/*" -path "./experiments/*" -path "./tools/*" -path "./syntax-visualizer/server/src/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
  - if find . -name "*.php" -path "./tests/*" -path "./validation/*" -maxdepth 0 --exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi

script:
  - composer validate
  - if [[ $STATIC_ANALYSIS = true ]]; then ./vendor/bin/phpstan analyse src --level=2; fi
  - |
    if [[ $TYPE = VALIDATION ]]; then
      ./vendor/bin/phpunit --testsuite validation
    elif [[ $TYPE = STATIC_ANALYSIS ]]; then
      pecl install -f ast-0.1.6
      composer require --dev phan/phan=dev-master
      vendor/bin/phan --color
    else
      ./vendor/bin/phpunit --testsuite invariants
      ./vendor/bin/phpunit --testsuite grammar
      ./vendor/bin/phpunit --testsuite api
    fi
